### ISSUE TITLE
Unmatched </li> in index.html.

### ISSUE THREAD

**Issue by zCoCo** [PlanetaryRobotics/iris_website#3]
@alessandra-11 
Unmatched `</li>` at line 87 in `index.html`. Not sure which </li> should be used. Probably will have to choose one.

[Image](https://pasteboard.co/JJnzAxY.png)

Raewyn asked me to take a look at the video issue and my IDE flagged this when I opened it up so I figured I'd raise the issue.

**Comment by cmumatt** [comment]
This issue was resolved by @ZhijieGao829 in commit a9cd6ed
